/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as AuthRouteImport } from './routes/_auth';
import { Route as AppRouteImport } from './routes/_app';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthRegisterRouteImport } from './routes/_auth/register';
import { Route as AuthLoginRouteImport } from './routes/_auth/login';
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard';
import { Route as AppUserIndexRouteImport } from './routes/_app/user/index';
import { Route as AppUserRoleIndexRouteImport } from './routes/_app/user-role/index';
import { Route as AppUserPermissionIndexRouteImport } from './routes/_app/user-permission/index';
import { Route as AppRoleIndexRouteImport } from './routes/_app/role/index';
import { Route as AppRolePermissionIndexRouteImport } from './routes/_app/role-permission/index';
import { Route as AppModelIndexRouteImport } from './routes/_app/model/index';
import { Route as AppFeatureIndexRouteImport } from './routes/_app/feature/index';
import { Route as AppDocumentSequenceIndexRouteImport } from './routes/_app/document-sequence/index';
import { Route as AppCategoryIndexRouteImport } from './routes/_app/category/index';
import { Route as AppCategoryAttributeIndexRouteImport } from './routes/_app/category-attribute/index';
import { Route as AppAttributeIndexRouteImport } from './routes/_app/attribute/index';
import { Route as AppAttributeGroupIndexRouteImport } from './routes/_app/attribute-group/index';
import { Route as AppAssetIndexRouteImport } from './routes/_app/asset/index';
import { Route as AppAllocationIndexRouteImport } from './routes/_app/allocation/index';
import { Route as AppAssetCreateRouteImport } from './routes/_app/asset/create';
import { Route as AppAssetBatchRouteImport } from './routes/_app/asset/batch';
import { Route as AppAssetIdEditRouteImport } from './routes/_app/asset/$id/edit';

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any);
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any);
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any);
const AppUserIndexRoute = AppUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AppRoute,
} as any);
const AppUserRoleIndexRoute = AppUserRoleIndexRouteImport.update({
  id: '/user-role/',
  path: '/user-role/',
  getParentRoute: () => AppRoute,
} as any);
const AppUserPermissionIndexRoute = AppUserPermissionIndexRouteImport.update({
  id: '/user-permission/',
  path: '/user-permission/',
  getParentRoute: () => AppRoute,
} as any);
const AppRoleIndexRoute = AppRoleIndexRouteImport.update({
  id: '/role/',
  path: '/role/',
  getParentRoute: () => AppRoute,
} as any);
const AppRolePermissionIndexRoute = AppRolePermissionIndexRouteImport.update({
  id: '/role-permission/',
  path: '/role-permission/',
  getParentRoute: () => AppRoute,
} as any);
const AppModelIndexRoute = AppModelIndexRouteImport.update({
  id: '/model/',
  path: '/model/',
  getParentRoute: () => AppRoute,
} as any);
const AppFeatureIndexRoute = AppFeatureIndexRouteImport.update({
  id: '/feature/',
  path: '/feature/',
  getParentRoute: () => AppRoute,
} as any);
const AppDocumentSequenceIndexRoute =
  AppDocumentSequenceIndexRouteImport.update({
    id: '/document-sequence/',
    path: '/document-sequence/',
    getParentRoute: () => AppRoute,
  } as any);
const AppCategoryIndexRoute = AppCategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => AppRoute,
} as any);
const AppCategoryAttributeIndexRoute =
  AppCategoryAttributeIndexRouteImport.update({
    id: '/category-attribute/',
    path: '/category-attribute/',
    getParentRoute: () => AppRoute,
  } as any);
const AppAttributeIndexRoute = AppAttributeIndexRouteImport.update({
  id: '/attribute/',
  path: '/attribute/',
  getParentRoute: () => AppRoute,
} as any);
const AppAttributeGroupIndexRoute = AppAttributeGroupIndexRouteImport.update({
  id: '/attribute-group/',
  path: '/attribute-group/',
  getParentRoute: () => AppRoute,
} as any);
const AppAssetIndexRoute = AppAssetIndexRouteImport.update({
  id: '/asset/',
  path: '/asset/',
  getParentRoute: () => AppRoute,
} as any);
const AppAllocationIndexRoute = AppAllocationIndexRouteImport.update({
  id: '/allocation/',
  path: '/allocation/',
  getParentRoute: () => AppRoute,
} as any);
const AppAssetCreateRoute = AppAssetCreateRouteImport.update({
  id: '/asset/create',
  path: '/asset/create',
  getParentRoute: () => AppRoute,
} as any);
const AppAssetBatchRoute = AppAssetBatchRouteImport.update({
  id: '/asset/batch',
  path: '/asset/batch',
  getParentRoute: () => AppRoute,
} as any);
const AppAssetIdEditRoute = AppAssetIdEditRouteImport.update({
  id: '/asset/$id/edit',
  path: '/asset/$id/edit',
  getParentRoute: () => AppRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/dashboard': typeof AppDashboardRoute;
  '/login': typeof AuthLoginRoute;
  '/register': typeof AuthRegisterRoute;
  '/asset/batch': typeof AppAssetBatchRoute;
  '/asset/create': typeof AppAssetCreateRoute;
  '/allocation/': typeof AppAllocationIndexRoute;
  '/asset/': typeof AppAssetIndexRoute;
  '/attribute-group/': typeof AppAttributeGroupIndexRoute;
  '/attribute/': typeof AppAttributeIndexRoute;
  '/category-attribute/': typeof AppCategoryAttributeIndexRoute;
  '/category/': typeof AppCategoryIndexRoute;
  '/document-sequence/': typeof AppDocumentSequenceIndexRoute;
  '/feature/': typeof AppFeatureIndexRoute;
  '/model/': typeof AppModelIndexRoute;
  '/role-permission/': typeof AppRolePermissionIndexRoute;
  '/role/': typeof AppRoleIndexRoute;
  '/user-permission/': typeof AppUserPermissionIndexRoute;
  '/user-role/': typeof AppUserRoleIndexRoute;
  '/user/': typeof AppUserIndexRoute;
  '/asset/$id/edit': typeof AppAssetIdEditRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/dashboard': typeof AppDashboardRoute;
  '/login': typeof AuthLoginRoute;
  '/register': typeof AuthRegisterRoute;
  '/asset/batch': typeof AppAssetBatchRoute;
  '/asset/create': typeof AppAssetCreateRoute;
  '/allocation': typeof AppAllocationIndexRoute;
  '/asset': typeof AppAssetIndexRoute;
  '/attribute-group': typeof AppAttributeGroupIndexRoute;
  '/attribute': typeof AppAttributeIndexRoute;
  '/category-attribute': typeof AppCategoryAttributeIndexRoute;
  '/category': typeof AppCategoryIndexRoute;
  '/document-sequence': typeof AppDocumentSequenceIndexRoute;
  '/feature': typeof AppFeatureIndexRoute;
  '/model': typeof AppModelIndexRoute;
  '/role-permission': typeof AppRolePermissionIndexRoute;
  '/role': typeof AppRoleIndexRoute;
  '/user-permission': typeof AppUserPermissionIndexRoute;
  '/user-role': typeof AppUserRoleIndexRoute;
  '/user': typeof AppUserIndexRoute;
  '/asset/$id/edit': typeof AppAssetIdEditRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_app': typeof AppRouteWithChildren;
  '/_auth': typeof AuthRouteWithChildren;
  '/_app/dashboard': typeof AppDashboardRoute;
  '/_auth/login': typeof AuthLoginRoute;
  '/_auth/register': typeof AuthRegisterRoute;
  '/_app/asset/batch': typeof AppAssetBatchRoute;
  '/_app/asset/create': typeof AppAssetCreateRoute;
  '/_app/allocation/': typeof AppAllocationIndexRoute;
  '/_app/asset/': typeof AppAssetIndexRoute;
  '/_app/attribute-group/': typeof AppAttributeGroupIndexRoute;
  '/_app/attribute/': typeof AppAttributeIndexRoute;
  '/_app/category-attribute/': typeof AppCategoryAttributeIndexRoute;
  '/_app/category/': typeof AppCategoryIndexRoute;
  '/_app/document-sequence/': typeof AppDocumentSequenceIndexRoute;
  '/_app/feature/': typeof AppFeatureIndexRoute;
  '/_app/model/': typeof AppModelIndexRoute;
  '/_app/role-permission/': typeof AppRolePermissionIndexRoute;
  '/_app/role/': typeof AppRoleIndexRoute;
  '/_app/user-permission/': typeof AppUserPermissionIndexRoute;
  '/_app/user-role/': typeof AppUserRoleIndexRoute;
  '/_app/user/': typeof AppUserIndexRoute;
  '/_app/asset/$id/edit': typeof AppAssetIdEditRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/asset/batch'
    | '/asset/create'
    | '/allocation/'
    | '/asset/'
    | '/attribute-group/'
    | '/attribute/'
    | '/category-attribute/'
    | '/category/'
    | '/document-sequence/'
    | '/feature/'
    | '/model/'
    | '/role-permission/'
    | '/role/'
    | '/user-permission/'
    | '/user-role/'
    | '/user/'
    | '/asset/$id/edit';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/asset/batch'
    | '/asset/create'
    | '/allocation'
    | '/asset'
    | '/attribute-group'
    | '/attribute'
    | '/category-attribute'
    | '/category'
    | '/document-sequence'
    | '/feature'
    | '/model'
    | '/role-permission'
    | '/role'
    | '/user-permission'
    | '/user-role'
    | '/user'
    | '/asset/$id/edit';
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/dashboard'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/asset/batch'
    | '/_app/asset/create'
    | '/_app/allocation/'
    | '/_app/asset/'
    | '/_app/attribute-group/'
    | '/_app/attribute/'
    | '/_app/category-attribute/'
    | '/_app/category/'
    | '/_app/document-sequence/'
    | '/_app/feature/'
    | '/_app/model/'
    | '/_app/role-permission/'
    | '/_app/role/'
    | '/_app/user-permission/'
    | '/_app/user-role/'
    | '/_app/user/'
    | '/_app/asset/$id/edit';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AppRoute: typeof AppRouteWithChildren;
  AuthRoute: typeof AuthRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_app': {
      id: '/_app';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_auth/register': {
      id: '/_auth/register';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof AuthRegisterRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/login': {
      id: '/_auth/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_app/dashboard': {
      id: '/_app/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof AppDashboardRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/user/': {
      id: '/_app/user/';
      path: '/user';
      fullPath: '/user/';
      preLoaderRoute: typeof AppUserIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/user-role/': {
      id: '/_app/user-role/';
      path: '/user-role';
      fullPath: '/user-role/';
      preLoaderRoute: typeof AppUserRoleIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/user-permission/': {
      id: '/_app/user-permission/';
      path: '/user-permission';
      fullPath: '/user-permission/';
      preLoaderRoute: typeof AppUserPermissionIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/role/': {
      id: '/_app/role/';
      path: '/role';
      fullPath: '/role/';
      preLoaderRoute: typeof AppRoleIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/role-permission/': {
      id: '/_app/role-permission/';
      path: '/role-permission';
      fullPath: '/role-permission/';
      preLoaderRoute: typeof AppRolePermissionIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/model/': {
      id: '/_app/model/';
      path: '/model';
      fullPath: '/model/';
      preLoaderRoute: typeof AppModelIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/feature/': {
      id: '/_app/feature/';
      path: '/feature';
      fullPath: '/feature/';
      preLoaderRoute: typeof AppFeatureIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/document-sequence/': {
      id: '/_app/document-sequence/';
      path: '/document-sequence';
      fullPath: '/document-sequence/';
      preLoaderRoute: typeof AppDocumentSequenceIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/category/': {
      id: '/_app/category/';
      path: '/category';
      fullPath: '/category/';
      preLoaderRoute: typeof AppCategoryIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/category-attribute/': {
      id: '/_app/category-attribute/';
      path: '/category-attribute';
      fullPath: '/category-attribute/';
      preLoaderRoute: typeof AppCategoryAttributeIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/attribute/': {
      id: '/_app/attribute/';
      path: '/attribute';
      fullPath: '/attribute/';
      preLoaderRoute: typeof AppAttributeIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/attribute-group/': {
      id: '/_app/attribute-group/';
      path: '/attribute-group';
      fullPath: '/attribute-group/';
      preLoaderRoute: typeof AppAttributeGroupIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/asset/': {
      id: '/_app/asset/';
      path: '/asset';
      fullPath: '/asset/';
      preLoaderRoute: typeof AppAssetIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/allocation/': {
      id: '/_app/allocation/';
      path: '/allocation';
      fullPath: '/allocation/';
      preLoaderRoute: typeof AppAllocationIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/asset/create': {
      id: '/_app/asset/create';
      path: '/asset/create';
      fullPath: '/asset/create';
      preLoaderRoute: typeof AppAssetCreateRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/asset/batch': {
      id: '/_app/asset/batch';
      path: '/asset/batch';
      fullPath: '/asset/batch';
      preLoaderRoute: typeof AppAssetBatchRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/asset/$id/edit': {
      id: '/_app/asset/$id/edit';
      path: '/asset/$id/edit';
      fullPath: '/asset/$id/edit';
      preLoaderRoute: typeof AppAssetIdEditRouteImport;
      parentRoute: typeof AppRoute;
    };
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute;
  AppAssetBatchRoute: typeof AppAssetBatchRoute;
  AppAssetCreateRoute: typeof AppAssetCreateRoute;
  AppAllocationIndexRoute: typeof AppAllocationIndexRoute;
  AppAssetIndexRoute: typeof AppAssetIndexRoute;
  AppAttributeGroupIndexRoute: typeof AppAttributeGroupIndexRoute;
  AppAttributeIndexRoute: typeof AppAttributeIndexRoute;
  AppCategoryAttributeIndexRoute: typeof AppCategoryAttributeIndexRoute;
  AppCategoryIndexRoute: typeof AppCategoryIndexRoute;
  AppDocumentSequenceIndexRoute: typeof AppDocumentSequenceIndexRoute;
  AppFeatureIndexRoute: typeof AppFeatureIndexRoute;
  AppModelIndexRoute: typeof AppModelIndexRoute;
  AppRolePermissionIndexRoute: typeof AppRolePermissionIndexRoute;
  AppRoleIndexRoute: typeof AppRoleIndexRoute;
  AppUserPermissionIndexRoute: typeof AppUserPermissionIndexRoute;
  AppUserRoleIndexRoute: typeof AppUserRoleIndexRoute;
  AppUserIndexRoute: typeof AppUserIndexRoute;
  AppAssetIdEditRoute: typeof AppAssetIdEditRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppAssetBatchRoute: AppAssetBatchRoute,
  AppAssetCreateRoute: AppAssetCreateRoute,
  AppAllocationIndexRoute: AppAllocationIndexRoute,
  AppAssetIndexRoute: AppAssetIndexRoute,
  AppAttributeGroupIndexRoute: AppAttributeGroupIndexRoute,
  AppAttributeIndexRoute: AppAttributeIndexRoute,
  AppCategoryAttributeIndexRoute: AppCategoryAttributeIndexRoute,
  AppCategoryIndexRoute: AppCategoryIndexRoute,
  AppDocumentSequenceIndexRoute: AppDocumentSequenceIndexRoute,
  AppFeatureIndexRoute: AppFeatureIndexRoute,
  AppModelIndexRoute: AppModelIndexRoute,
  AppRolePermissionIndexRoute: AppRolePermissionIndexRoute,
  AppRoleIndexRoute: AppRoleIndexRoute,
  AppUserPermissionIndexRoute: AppUserPermissionIndexRoute,
  AppUserRoleIndexRoute: AppUserRoleIndexRoute,
  AppUserIndexRoute: AppUserIndexRoute,
  AppAssetIdEditRoute: AppAssetIdEditRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthRegisterRoute: typeof AuthRegisterRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
