/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as AuthRouteImport } from './routes/_auth';
import { Route as AppRouteImport } from './routes/_app';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthRegisterRouteImport } from './routes/_auth/register';
import { Route as AuthLoginRouteImport } from './routes/_auth/login';
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard';
import { Route as AppUserIndexRouteImport } from './routes/_app/user/index';
import { Route as AppCategoryIndexRouteImport } from './routes/_app/category/index';
import { Route as AppCategoryAttributeIndexRouteImport } from './routes/_app/category-attribute/index';
import { Route as AppAttributeIndexRouteImport } from './routes/_app/attribute/index';

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any);
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any);
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any);
const AppUserIndexRoute = AppUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AppRoute,
} as any);
const AppCategoryIndexRoute = AppCategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => AppRoute,
} as any);
const AppCategoryAttributeIndexRoute =
  AppCategoryAttributeIndexRouteImport.update({
    id: '/category-attribute/',
    path: '/category-attribute/',
    getParentRoute: () => AppRoute,
  } as any);
const AppAttributeIndexRoute = AppAttributeIndexRouteImport.update({
  id: '/attribute/',
  path: '/attribute/',
  getParentRoute: () => AppRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/dashboard': typeof AppDashboardRoute;
  '/login': typeof AuthLoginRoute;
  '/register': typeof AuthRegisterRoute;
  '/attribute/': typeof AppAttributeIndexRoute;
  '/category-attribute/': typeof AppCategoryAttributeIndexRoute;
  '/category/': typeof AppCategoryIndexRoute;
  '/user/': typeof AppUserIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/dashboard': typeof AppDashboardRoute;
  '/login': typeof AuthLoginRoute;
  '/register': typeof AuthRegisterRoute;
  '/attribute': typeof AppAttributeIndexRoute;
  '/category-attribute': typeof AppCategoryAttributeIndexRoute;
  '/category': typeof AppCategoryIndexRoute;
  '/user': typeof AppUserIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_app': typeof AppRouteWithChildren;
  '/_auth': typeof AuthRouteWithChildren;
  '/_app/dashboard': typeof AppDashboardRoute;
  '/_auth/login': typeof AuthLoginRoute;
  '/_auth/register': typeof AuthRegisterRoute;
  '/_app/attribute/': typeof AppAttributeIndexRoute;
  '/_app/category-attribute/': typeof AppCategoryAttributeIndexRoute;
  '/_app/category/': typeof AppCategoryIndexRoute;
  '/_app/user/': typeof AppUserIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/attribute/'
    | '/category-attribute/'
    | '/category/'
    | '/user/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/attribute'
    | '/category-attribute'
    | '/category'
    | '/user';
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/dashboard'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/attribute/'
    | '/_app/category-attribute/'
    | '/_app/category/'
    | '/_app/user/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AppRoute: typeof AppRouteWithChildren;
  AuthRoute: typeof AuthRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_app': {
      id: '/_app';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_auth/register': {
      id: '/_auth/register';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof AuthRegisterRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/login': {
      id: '/_auth/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_app/dashboard': {
      id: '/_app/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof AppDashboardRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/user/': {
      id: '/_app/user/';
      path: '/user';
      fullPath: '/user/';
      preLoaderRoute: typeof AppUserIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/category/': {
      id: '/_app/category/';
      path: '/category';
      fullPath: '/category/';
      preLoaderRoute: typeof AppCategoryIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/category-attribute/': {
      id: '/_app/category-attribute/';
      path: '/category-attribute';
      fullPath: '/category-attribute/';
      preLoaderRoute: typeof AppCategoryAttributeIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/attribute/': {
      id: '/_app/attribute/';
      path: '/attribute';
      fullPath: '/attribute/';
      preLoaderRoute: typeof AppAttributeIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute;
  AppAttributeIndexRoute: typeof AppAttributeIndexRoute;
  AppCategoryAttributeIndexRoute: typeof AppCategoryAttributeIndexRoute;
  AppCategoryIndexRoute: typeof AppCategoryIndexRoute;
  AppUserIndexRoute: typeof AppUserIndexRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppAttributeIndexRoute: AppAttributeIndexRoute,
  AppCategoryAttributeIndexRoute: AppCategoryAttributeIndexRoute,
  AppCategoryIndexRoute: AppCategoryIndexRoute,
  AppUserIndexRoute: AppUserIndexRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthRegisterRoute: typeof AuthRegisterRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
