export const ENDPOINTS = {
  AUTH: '/auth',
  ATTRIBUTE_GROUPS: '/attribute-groups',
  ATTRIBUTES: '/attributes',
  CATEGORIES: '/categories',
  CATEGORY_ATTRIBUTES: '/category-attributes',
  FEATURES: '/features',
  MODEL_ATTRIBUTE_VALUES: '/model-attribute-values',
  MODELS: '/models',
  ROLES: '/roles',
  ROLE_PERMISSIONS: '/role-permissions',
  USER_PERMISSIONS: '/user-permissions',
  USER_ROLES: '/user-roles',
  USERS: '/users',
} as const;
