export const FEATURES = {
  ASSET: 'ASSET',
  ATTRIBUTE_GROUP: 'ATTRIBUTE_GROUP',
  CATEGORY: 'CATEGORY',
  ATTRIBUTE: 'ATTRIBUTE',
  DOCUMENT_SEQUENCE: 'DOCUMENT_SEQUENCE',
  MODEL: 'MODEL',
  ROLE: 'ROLE',
  USER: 'USER',
  FEATURE: 'FEATURE',
} as const;

export type Feature = (typeof FEATURES)[keyof typeof FEATURES];
